name: Aggiornamento Portfolio Pokemon

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Installa dipendenze
        run: |
          pip install -r requirements.txt
          
      - name: Esegui lo script
        env:
          CARDTRADER_TOKEN: ${{ secrets.CARDTRADER_TOKEN }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python tracker.py
